version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/appropriatesolutions/appropriatesolutions
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/appropriatesolutions
      - node/with-cache:
          steps:
            - run: pwd
            - run: ls -al
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
