version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/appropriatesolutions/appropriatesolutions
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/appropriatesolutions
      - node/with-cache:
          cache-key: 'package-lock.json'
          steps:
            - run: npm install
            - run: npm test
            - add_ssh_keys:
                fingerprints:
                  - 'e9:fd:ed:0b:56:b9:39:97:6d:9f:6d:d3:b1:8c:e3:f2'
            - run:
                name: Deploy tp GH Pages
                command: |
                  git config user.email "appsol@gmail.com"
                  git config user.name "appsol"
                  npm run deploy
            - store_artifacts:
                path: test-results.xml
                prefix: tests
            - store_test_results:
                path: test-results.xml
workflows:
  build-and-test:
    jobs:
      - build-and-test
